# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.CharField(default='Size', max_length=100),
        ),
    ]
