# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0007_products_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cat',
        ),
        migrations.AddField(
            model_name='products',
            name='primary_usage',
            field=models.CharField(blank=True, choices=[('Usage', (('new', 'New Strains'), ('headache', 'Headache'), ('insomnia', 'Insomnia'), ('social', 'Fun With Friends'), ('first_time', 'First Timers'), ('women', 'Menstrual Crams & Pains'), ('body', 'Body Pains'), ('stress', 'Stress and Tension'), ('creative', 'Creativity'), ('productive', 'Productivity'), ('food', 'Edibles'), ('oils', 'Oils & Dabs'), ('acc', 'Accessories')))], max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='secondary_usage',
            field=models.CharField(blank=True, choices=[('Usage', (('new', 'New Strains'), ('headache', 'Headache'), ('insomnia', 'Insomnia'), ('social', 'Fun With Friends'), ('first_time', 'First Timers'), ('women', 'Menstrual Crams & Pains'), ('body', 'Body Pains'), ('stress', 'Stress and Tension'), ('creative', 'Creativity'), ('productive', 'Productivity'), ('food', 'Edibles'), ('oils', 'Oils & Dabs'), ('acc', 'Accessories')))], max_length=20),
        ),
    ]
