# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0008_auto_20180113_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.CharField(blank=True, choices=[('Sizes', (('half', 'Half Gram'), ('gram', 'Gram'), ('eighth', 'Eighth Ounce'), ('quarter', 'Quarter Ounce'), ('half', 'Half Ounce'), ('oz', 'Ounce')))], max_length=100),
        ),
    ]
