# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0010_auto_20180113_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Your Order Is Being Picked Right Off The Plant!'), (2, 'Picked, Measured, And Ready For Delivery.'), (3, 'The Best Bud Is Heading Straight To Your Door.'), (4, 'Delivered')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddysapp.Customer')),
                ('dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddysapp.Dispensary')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddysapp.Driver')),
            ],
        ),
    ]
