# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0014_auto_20180114_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='products',
        ),
    ]
