# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0016_auto_20180116_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buddysapp.Driver'),
        ),
    ]
