# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddysapp', '0017_auto_20180117_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='products',
            new_name='product',
        ),
    ]
